### ISSUE TITLE
Naive method not working

### ISSUE THREAD

**Issue by AashikaVasraTR** [bnjbvr/Knights-Tour#1]
Hi,
When I commented the heuristic method and went on with the naive method, the code didn't work.  After giving the command go., there was no output and the cursor kept blinking for a long time.  For naive method also, we are supposed to compile code, answer the questions and then go, right?  Is my way of execution correct?  Correct me if I am wrong.

I have attached a screenshot of the output as a proof.
![image](https://user-images.githubusercontent.com/43838275/49037698-c8f58e80-f16f-11e8-99b0-7c85739f002a.png)

**Comment by bnjbvr** [comment]
Hi! To be fair, this was a school project and so it's unmaintained. That being said, from what I recall the naive method can be very slow, even on small chessboards, hence the need for the heuristic-based one. Maybe try with smaller chessboards (starting with 3x3) and see if you get a quick answer for those with the naive method?

**Comment by AashikaVasraTR** [comment]
Yeah as you said, it works after a really long time.  It works.  Thank you:)  3x3 takes a shorted time when compared to 8x8.
